---
- hosts: all
  vars_files:
  - vars.yaml
  tasks:
  # OpenVPN server dependencies
  - block:
    - set_fact: required_vars={{required_vars_by_task.server_dependencies}}
    - include: tasks/server_dependencies.yaml
  # OpenVPN server configuration
  - block:
    - set_fact: required_vars={{required_vars_by_task.server_configuration}}
    - include: tasks/server_configuration.yaml
  # OpenVPN client configuration
  - block:
    # Create an empty variable with the same name as the loop variable below.
    # This variable must exist before the loop begins or it will not be
    # available to the included tasklist (even though the loop sets it each
    # iteration).
    - set_fact: openvpn_client_name=""
    - set_fact: required_vars={{required_vars_by_task.client}}
    - include: tasks/client.yaml
      with_items: "{{openvpn_client_names}}"
      loop_control:
        loop_var: openvpn_client_name
    - name: Restart openvpn service
      systemd: name=openvpn state=restarted
      become: yes
